version: '3'

services:
  db:
    build: ./db
    image: artist-db:0.0.1
    container_name: artist-db
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artist
      MYSQL_USER: artist
      MYSQL_PASSWORD: artist

volumes:
  db:
    driver: local